version: "3.8"

services:
  django:
    image: theormove/docker_tutorial:django
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "$HOST_PORT:$DOCKER_PORT"

