# Generated by Django 4.1.2 on 2022-10-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300, unique=True)),
                ('vector', models.CharField(default='0', max_length=300, unique=True)),
                ('picture', models.ImageField(upload_to='pictures/')),
            ],
        ),
    ]
