# Generated by Django 4.1.2 on 2022-11-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_dish_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='picture',
            field=models.ImageField(blank=True, upload_to='pictures/'),
        ),
    ]
