# Generated by Django 4.1.2 on 2022-12-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_dish_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishes_array', models.JSONField()),
                ('correct_guesses', models.JSONField(blank=True)),
                ('incorrect_guesses', models.JSONField(blank=True)),
            ],
        ),
    ]
