# Generated by Django 4.1.2 on 2023-01-05 08:52

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_dishset_correct_guesses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dishset',
            name='correct_guesses',
            field=models.JSONField(default=api.models.jsonfield_default_value),
        ),
        migrations.AlterField(
            model_name='dishset',
            name='dishes_array',
            field=models.JSONField(default=api.models.jsonfield_default_value),
        ),
        migrations.AlterField(
            model_name='dishset',
            name='incorrect_guesses',
            field=models.JSONField(default=api.models.jsonfield_default_value),
        ),
    ]
